### ISSUE TITLE
Pytorch GPU Installation

### ISSUE THREAD

**Issue by AntiDoctor** [QVPR/Patch-NetVLAD#13]
Could be good to change the installation instructions for Conda/Mamba to include Pytorch GPU instead of CPU as this throws an error out of the box. 

Also minor typo:

https://github.com/QVPR/Patch-NetVLAD/blob/9593f38bca7233b3d35c1f0b012348039789fc66/match_two.py#L151 

opt.plot_save_path -> plot_save_path?

**Comment by StephenHausler** [comment]
Hi AntiDoctor, we will update the instructions, thanks for this suggestion.
Also thanks for picking up this bug, yep it should be plot_save_path. This bug has been fixed now.
