### ISSUE TITLE
About reproduce the results in the paper

### ISSUE THREAD

**Issue by CaiYingFeng** [QVPR/Patch-NetVLAD#15]
Hi,
I'm trying to reproduce the Single-Spatial-Patch-NetVLAD on the Pitts30k datasets. I used pitts_WPCA512.pth.tar to calculate netvlad descriptor of patch.  I got recall@1=87.09, recall@5=94.05, recall@10=95.67. Recall@5 and recall@10 are same as them in paper (Table 2), but recall@1=88.0 in the paper. Besides, in the paper Single-Spatial-Patch-NetVLAD recall@1=88 is higher performance than Single-RANSAC-Patch-NetVLAD recall@1=87.3. Could you please reconfirm the accuracy of the data (recall@1=88 in table 2 pitts30k use Single-Spatial-Patch-NetVLAD method) and could you please tell me how can i reproduce the results in the paper.

**Comment by StephenHausler** [comment]
Hi @CaiYingFeng, the results in Table 2 are all done using WPCA4096. The only results that use WPCA512 in the paper are those in Figure 4. Try running Single Spatial but with WPCA4096 and that should fix the numbers. As to Spatial being better than RANSAC, we did notice that can happen in some datasets.

**Comment by Tobias-Fischer** [comment]
Also, in addition to Stephen's comments, we re-trained the network for the public code release and there might be minor deviations in the results obtained using the new network with those from what is reported in the paper (we checked that they are generally <1% difference in recall, sometimes they are slightly better than what is reported in the paper, sometimes slightly worse).

Feel free to re-open if you have further questions @CaiYingFeng.
