### ISSUE TITLE
How to convert h5 files to npz

### ISSUE THREAD

**Issue by DonMuv** [QVPR/Patch-NetVLAD#16]
Does anyone know how to convert h5 files to npz format?  the ground truth files of some data sets are h5 files

**Comment by Tobias-Fischer** [comment]
Hi @DonMuv,
Do you happen to have an example for a dataset in which that is the case? You can take a similar approach to https://stackoverflow.com/questions/46733052/read-hdf5-file-into-numpy-array in general, but we might be able to help if you have specific examples.

**Comment by DonMuv** [comment]
Hi @Tobias-Fischer ,
I want to use the TB-Places dataset, but its ground truth file is .h5 format, see https://github.com/marialeyvallina/TB_Places, can you help me?

**Comment by DonMuv** [comment]
Hi @Tobias-Fischer ,
Sorry to disturb you, I have solved this problem, thank you very much

**Comment by Tobias-Fischer** [comment]
Great! Thanks for letting us know.
