### ISSUE TITLE
Does utmQ correspond to the query file or the index file?

### ISSUE THREAD

**Issue by DonMuv** [QVPR/Patch-NetVLAD#18]
I have another problem, i don't know utmQ correspond to the query file or the index file, because when utmQ corresponds to the query file, the recalls are all 1.0

**Comment by StephenHausler** [comment]
Hi @DonMuv, utmQ corresponds to the query file. Hmm not sure what's happening there, which dataset specifically were you using? If you are using our provided gt files for tokyo, nordland or pitts they should just work "as is" without needing to modify the gt files.

**Comment by Tobias-Fischer** [comment]
Closing here due to inactivity - feel free to reopen @DonMuv
