### ISSUE TITLE
About the hard disk memory

### ISSUE THREAD

**Issue by Hanoch-ZH** [QVPR/Patch-NetVLAD#19]
Hi, thanks for sharing your work.
I have a question. After I ran the _feature_extract.py_, the size of produced files is over 800G, is it normal?
I even cannot extract query images' features due to the lack of disk memory.

**Comment by StephenHausler** [comment]
Hi @Hanoch-ZH, yes that could be normal. If you are trying to run a really large dataset, like Nordland, that's expected for the performance version of our work. Couple options, you could use one of the smaller PCA models (modify performance.ini to change the model used), or use speed.ini.

**Comment by Tobias-Fischer** [comment]
storage.ini uses 128-d descriptors, compared to the default 4096-d descriptors. So that's a lot less storage required.

**Comment by Hanoch-ZH** [comment]
@Tobias-Fischer @StephenHausler Thank you. I will try it and your work is really great!
