### ISSUE TITLE
Code is missing

### ISSUE THREAD

**Issue by Zumbalamambo** [QVPR/Patch-NetVLAD#2]
Please add an example to train on custom dataset and to do predictions

**Comment by Tobias-Fischer** [comment]
Dear @Zumbalamambo, many thanks for your interest in our work. As stated in the readme, the code will follow at a later stage, but before CVPR2021. I will close this issue for now - please star the repository so you will get updated once the code will be available.

Many thanks!

**Comment by Zumbalamambo** [comment]
@Tobias-Fischer please also add an options to train on custom dataset :P
