### ISSUE TITLE
Question about Nordland dataset.

### ISSUE THREAD

**Issue by Jinyu-M** [QVPR/Patch-NetVLAD#21]
Hi, thanks for your work. I have a question about Nordland dataset.
The Nordland dataset downloaded from [https://nrkbeta.no/2013/01/15/nordlandsbanen-minute-by-minute-season-by-season/]
is a video. What's frequency do you extract frames? Can you provide your related codes or used images dataset? Thanks.

Best regards.

**Comment by Tobias-Fischer** [comment]
Hi, we extract the frames at 1fps. We'll check whether we can provide access to the dataset directly.

**Comment by Jinyu-M** [comment]
Thanks for your reply.

**Comment by gmberton** [comment]
Hello, are there any news on this topic?
It would be great to have the chance to download the dataset directly, as it would avoid possible inconsistencies.
Also, there shouldn't be any legal issue given that it is licensed under Creative Commons :-)
