### ISSUE TITLE
Does this training code support Pittsburgh dataset?

### ISSUE THREAD

**Issue by Hanoch-ZH** [QVPR/Patch-NetVLAD#24]
Hi, Thanks for sharing your training code. 
It seems that it only supports Mapillary Dataset, If I want to train the Pittsburgh Dataset, what should I do?

Thanks for your help.

**Comment by Tobias-Fischer** [comment]
Hi @Hanoch-ZH,

Many thanks for your interest in our work! If you want to train on Pittsburgh, please refer to [this repo](https://github.com/Nanne/pytorch-NetVlad). The trained models are compatible with our code, i.e. and you can load them and do inference with our code.
