### ISSUE TITLE
how to reproduce Mapillary val recall

### ISSUE THREAD

**Issue by ZZQzzq** [QVPR/Patch-NetVLAD#26]
Hi, I have some question about the result reproduction of Mapillary val, the results reported in paper is the mean value of recall per each city or the value that test all queries on all database composed of all cities？could you tell more details about this, thank you very much!

**Comment by Tobias-Fischer** [comment]
Hi there,
We first obtain the predictions separately for the validation cities (cph and sf). We then concatenate the files (`cat mapillarycph.csv mapillarysf.csv > mapillaryval.csv`) and finally use the official evaluation script to obtain the recall results:
```bash
python ./mapillary_sls/evaluate.py --msls-root=/path/to/Mapillary_Street_Level_Sequences --cities=cph,sf --prediction=mapillaryval.csv
```

I hope this helps - feel free to reopen if you have more questions.

**Comment by Anuradha-Uggi** [comment]
Dear Fischer, 
You have done a great job. The current Github includes ground truths for Nordland, Pittsburgh 30k, and Tokyo 24/7. It would be helpful for us if you could provide the datasets and the ground truth npz files/links for RobotCar Seasons v2, Extended CMU Seasons, and Mapillary Street Level Sequences (MSLS).
Thank you very much.
