### ISSUE TITLE
PackageNotFoundError

### ISSUE THREAD

**Issue by jaaaaaang** [QVPR/Patch-NetVLAD#28]
hi, before i ask you , thanks for sharing this cool Patch-NetVLAD

I am trying use this, but It is not easy (i am a beginner)

 I typed below code in the conda prompt,  (this is the installation you said)
-----------------------------------------------------------
conda create -n patchnetvlad python=3.8 numpy pytorch-gpu torchvision natsort tqdm opencv pillow scikit-learn faiss matplotlib-base -c conda-forge
conda activate patchnetvlad
------------------------------------------------------------
but it doesn't work.
I got this message : Solving environment: failed with repodata from current_repodata.json,
and then finally it failed. 

please let me know how to fix this problem and 
as far as you know (with a good heart) please tell me how to use this NetVLAD 👍

I want to test like below: 
1. one street image (image no.1)
2. five random place images (one of them is around of image no.1)
3. so i want to match them.

have a nice day

**Comment by Tobias-Fischer** [comment]
Hi,

Could you please try the following commands?
```bash
conda install mamba
mamba create -n patchnetvlad2 python=3.8 numpy pytorch-gpu torchvision natsort tqdm opencv pillow scikit-learn faiss matplotlib-base -c conda-forge
```

Please refer to https://github.com/QVPR/Patch-NetVLAD/blob/main/match_two.py which shows how to use our code to match images.

**Comment by jaaaaaang** [comment]
really thanks, but I already installed mamba and then tried.
i think it's my problem.

have a nice day.

**Comment by Tobias-Fischer** [comment]
What is the error when running
```
mamba create -n patchnetvlad2 python=3.8 numpy pytorch-gpu torchvision natsort tqdm opencv pillow scikit-learn faiss matplotlib-base -c conda-forge
```
?
