### ISSUE TITLE
keywords: 'optimizer' and 'epoch'

### ISSUE THREAD

**Issue by cxy1996** [QVPR/Patch-NetVLAD#31]
hi :)
Can you tell me why there are no 'optimizer' and 'epoch' keywords when I load your model（mapillary_WPCA4096.pth.tar）？
thanks

**Comment by Tobias-Fischer** [comment]
Hi,
this is because we don't save those keywords when adding the PCA layer in https://github.com/QVPR/Patch-NetVLAD/blob/main/add_pca.py

Feel free to open a PR adding those keywords if you need them for some reason.

**Comment by cxy1996** [comment]
Thanks, great work!
