### ISSUE TITLE
Indoor experiment

### ISSUE THREAD

**Issue by oym1994** [QVPR/Patch-NetVLAD#32]
Hi, thanks for your great contribution. Here I want to consult some questions about indoor experiment.

In the paper, all experements are conducted in outdoor datasets. I wander what would be the difference if applying 
it into a real indoor enviroment, such as home, official and even some room with repeat region(such as a Server Room where many server computers with the same apperiance are placed)?  How can I get the training dataset without GPS in indoor room?
Thanks for your attention and I am always looking forward to your kind response and any advice.

Best regards,
Slamer

**Comment by Tobias-Fischer** [comment]
Hi Slamer,

Indoor place recognition brings its own challenges indeed. There are some indoor place rec datasets - see e.g. the VPR-Bench paper for an overview.

You don't necessarily need GPS information. To train the network all you need is a list of query images, a set of potential positives for each query, and a list of definite negatives for each query. GPS information provides a convenient way of obtaining those positives and negatives.

I would recommend reading through some recent papers on indoor place recognition to see how this is typically being done in that context.

Please let us know if you have any more specific questions.


Best, Tobi

**Comment by oym1994** [comment]
Hi, Thanks for your kind response. As you have advised, I should read through some papers related to indoor place recognition. Waiting for your next great work!
