### ISSUE TITLE
sorry，how i can get the dataset

### ISSUE THREAD

**Issue by XiaozhuLove** [QVPR/Patch-NetVLAD#33]
sorry，i can not find the whole Pittsburgh30k or  Pittsburgh250k dataset after Google many times。I'm at the end of my rope。Therefore I can not but seek your help，Could you tell me convenient how i can get the dataset。think you very much！Excuse me for such a question。

**Comment by Tobias-Fischer** [comment]
Please see https://www.di.ens.fr/willow/research/netvlad/
