### ISSUE TITLE
can't assign a tuple to a torch.cuda.FloatTensor

### ISSUE THREAD

**Issue by DonMuv** [QVPR/Patch-NetVLAD#35]
Hi,
I get this error 'can't assign a tuple to a torch.cuda.FloatTensor' when I run train.py, and pooling = patchnetvlad in train.ini.
The place where the error occurred is:
vlad_encoding = net.pool(image_encoding)
pvecs[i * bs:(i + 1) * bs, :] = vlad_encoding
and
vlad_encoding：
([tensor([[[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., 

But when pooling = netvlad in train.ini
vlad_encoding：
tensor([[[-5.1483e-03, -2.0104e-02,  0.0000e+00,  ...,
The above error will not appear

**Comment by Tobias-Fischer** [comment]
Hi, please refer to https://github.com/QVPR/Patch-NetVLAD/issues/27

In short, training with patchnetvlad pooling doesn't work - instead train with netvlad pooling and then apply patchnetvlad pooling at inference time.
