### ISSUE TITLE
Code Release Date

### ISSUE THREAD

**Issue by AntiDoctor** [QVPR/Patch-NetVLAD#4]
Hi there, 

I'm working on a related project for submission to CoRL 2021 and would like to use this system for comparison. The deadline for CoRL submission is on the 18th June 2021, I was just wondering whether the code is on track for being available by the 1st of June?

Regards,

Will

**Comment by Tobias-Fischer** [comment]
Hi Will,
Yes, we're on track :). The code itself is ready, we're just re-running the experiments to make sure the results are consistent with what we report in the paper.

Best, Tobi

**Comment by AntiDoctor** [comment]
> Hi Will,
> Yes, we're on track :). The code itself is ready, we're just re-running the experiments to make sure the results are consistent with what we report in the paper.
> 
> Best, Tobi

Awesome, thank you!
