### ISSUE TITLE
Incorrect Aachen Day-Night result

### ISSUE THREAD

**Issue by HeartbreakSurvivor** [QVPR/Patch-NetVLAD#46]
Hi, I tried to use your pretrained pittsburgh_WPCA4096 model to test on Aachen Day-Night dataset, but got totally incorrect result.
here is my complete process.
  1. generate `Aachen_db_path.txt` and `Aachen_query_path.txt`
   
  2.  run the `feature_extract.py` for db and query images use following two commands. 
```
python feature_extract.py \
  --config_path patchnetvlad/configs/speed.ini \
  --dataset_file_path=Aachen_db_path.txt \
  --output_features_dir patchnetvlad/output_features/aachen_index

python feature_extract.py \
  --config_path patchnetvlad/configs/speed.ini \
  --dataset_file_path=Aachen_query_path.txt \
  --output_features_dir patchnetvlad/output_features/aachen_query
```
  3. run the 'feture_match.py' for feature matching without providing ground_truth_path
```
python feature_match.py \
  --config_path patchnetvlad/configs/speed.ini \
  --query_file_path=Aachen_query_path.txt \
  --index_file_path=Aachen_db_path.txt \
  --query_input_features_dir patchnetvlad/output_features/aachen_query \
  --index_input_features_dir patchnetvlad/output_features/aachen_index \
  --result_save_folder patchnetvlad/results/aachen_subset
```
  3. then process `PatchNetVLAD_predictions.txt`, for each query image it output top 100 reference images. I just used the pose of top1 reference image as the estimated pose of each query image and post the result to [benchmark](https://www.visuallocalization.net/), but got totally wrong result. here is the result:
  
![image](https://user-images.githubusercontent.com/16981274/145706035-40b5a580-276e-4021-9811-8bad667f049b.png)

  I want to know what's wrong with my steps and why it outputs such unacceptable results. Is the model version that I used is wrong? Or have you test your models on Aachen dataset, if you did, could you please provide the result ?

**Comment by Tobias-Fischer** [comment]
@mingu6 - I remember you wrote the original Aachen script that we used. Any hints?

**Comment by HeartbreakSurvivor** [comment]
> @mingu6 - I remember you wrote the original Aachen script that we used. Any hints?

Hi, I have solved this problem, you can close this issue, thank you for your reply.

**Comment by HeartbreakSurvivor** [comment]
Hi, I have solved this problem, thank you for your reply.

**Comment by Tobias-Fischer** [comment]
Could you please let us know how you solved it?

**Comment by HeartbreakSurvivor** [comment]
> 

the result file `PatchNetvlad_predictions.txt` is in Kapture Format, it split query and db images by `, `,  but I didn't notice it, so the file I submit to benchmark websit is incorrect. just like this:
> dusk/rear/1424450493097851.jpg, 0.759246 -0.627745 0.105474 0.135487 418.51807066856844 -58.480848029973274 330.23423009472407

So I got totally wrong result which contains all zeros, it seems that if your submit file's format is incorrect, it will output all zeros, just a tips I learned from this issues.
