### ISSUE TITLE
Some questions about loss and GPU memory

### ISSUE THREAD

**Issue by JinRanYAO** [QVPR/Patch-NetVLAD#47]
Hello Stephen, thanks for your excellent work. I have some questions about Patch-NetVLAD: Which loss function did you use in Patch-NetVLAD? Is it the triplet loss same as in NetVLAD? But I think the triplet loss is used to evaluate the full image, is it suitable for patch and how to modify it to use it to evaluate patch? And how much GPU memory I need to run the train code of Patch-NetVLAD?
Looking forward to your reply!

**Comment by Tobias-Fischer** [comment]
Hi @JinRanYAO,

We indeed use the standard triplet loss, and train the global descriptors (for the full image). We then apply these learned descriptors on the patches. For more information, please see https://github.com/QVPR/Patch-NetVLAD/issues/27

I am not sure about exact numbers regarding GPU memory, but 8 or 12 Gb should be sufficient.

I hope this helps - feel free to reopen if you have more questions.
