### ISSUE TITLE
Reproduce the results of DELG in the paper

### ISSUE THREAD

**Issue by hellocasper** [QVPR/Patch-NetVLAD#50]
Hi, thank you for sharing this great work. In the official paper, DELG achieves the top performance on some datasets. May I know how to reproduce those results of DELG? Do you use the pre-trained model or fine-tune it on Pitts30k/MSLS?

**Comment by Tobias-Fischer** [comment]
Hi @hellocasper, we use the pre-trained model from the authors' repository: https://github.com/tensorflow/models/blob/master/research/delf/delf/python/delg/DELG_INSTRUCTIONS.md

Hope that helps.

**Comment by hellocasper** [comment]
Hi @Tobias-Fischer, thanks for your help and quick reply! Should I transfer the model to PyTorch first, as I notice the official repository is based on TensorFlow?

**Comment by Tobias-Fischer** [comment]
We used the official repository without any changes (i.e. we used tensorflow) for the DELG comparisons.

**Comment by hellocasper** [comment]
OK, thanks! @Tobias-Fischer
