### ISSUE TITLE
Why only train conv5 of VGG?

### ISSUE THREAD

**Issue by jmorlana** [QVPR/Patch-NetVLAD#51]
Hi! First of all, congratulations for your great work, very inspiring! I would like to know the reasons for only training the last layers of VGG instead of the full network. Have you tried to see if the results improve? I recall the original NetVLAD paper also did this for memory reasons, but GPUs are more powerful now. 

Thank you and congrats again!

**Comment by Tobias-Fischer** [comment]
Hi @jmorlana, many thanks for your interest in our work, and for your kind words. We have not tried to train all VGG layers - indeed this might improve performance. In the NetVLAD TPAMI paper, Table 2, they performed some experiments with AlexNet - there the difference between training just the last conv layer or the whole network wasn't too big.

Feel free to report back if you decide to train the all VGG layers.
