### ISSUE TITLE
How to down NordLand test dataset

### ISSUE THREAD

**Issue by HeartbreakSurvivor** [QVPR/Patch-NetVLAD#53]
Hi, I really appreciate for the work you've done.
I want to test PatchNetvlad on NordLand dataset , so I download NordLand dataset from [here](https://drive.google.com/drive/folders/1SmrDOeUgBnJbpW187VFWxGjS7XdbZK5t), but the dataset seems not the the same as your provided `nordland_imageNames_query.txt`, `nordland_imageNames_index.txt` . besides,  the datasets I have downloaded do not provide ground truth file, so could  you please tell me how can I get NordLand test dataset?

**Comment by Tobias-Fischer** [comment]
Hi,

You can download the full dataset from here: https://nrkbeta.no/2013/01/15/nordlandsbanen-minute-by-minute-season-by-season/

You can then extract 1 frame per second using e.g. ffmpeg (see https://nikosuenderhauf.github.io/assets/papers/openseqslam.pdf). The videos are pre-synchronised, such that frame X in one traverse is the same place as frame X in any of the other traverses.

**Comment by HeartbreakSurvivor** [comment]
Thanks
