### ISSUE TITLE
About “out of memory” question

### ISSUE THREAD

**Issue by buulzj** [QVPR/Patch-NetVLAD#55]
Hello, My question is "OSError: Not enough free space to write 18530304 bytes" in feature extract process.

It seems to be that Numpy.save() needs more memory than I have.

My computer have 16GB Memory, 200GB free Disk space and WSL2 Ubuntu20.04 OS. 

The WSL2 needs 3GB Memory to keep working.

Can you give me some advice?

Thank you.

**Comment by Tobias-Fischer** [comment]
The error is quite specific, you're out of disk space on the partition that you want to write to. Why do you use WSL? You should be able to install everything directly on Windows using mamba. Or maybe change the path where you save the files to?

**Comment by buulzj** [comment]
Thank you for your guidance. I will try to experiment on Windows platform.
