### ISSUE TITLE
Shape of Local features

### ISSUE THREAD

**Issue by wjun0830** [QVPR/Patch-NetVLAD#56]
Hi.
Thanks for interesting work.

I'm curious about the shape of local features.
Local feature seems to have the shape of 1131, 4096 when the size of the patch is 3.
And 1131 seems to be the number of patch.
Still, I don't get how 1131 is computed.
May I ask how the number of 1131 is computed?

Regards

**Comment by StephenHausler** [comment]
Number of patches = (W-1)*(H-1) = 39*29 (for an input image of size 640x480)
Where W is the width of the feature map at Vgg-16 conv5 and H is the height.
The number of patches is based on the stride (we set to 1) and the size of the feature map.

Let me know if you have any further questions :)
