### ISSUE TITLE
Downloading Nordland dataset

### ISSUE THREAD

**Issue by gmberton** [QVPR/Patch-NetVLAD#57]
Hi, will you release your version of the Nordland dataset?
It would be great to have the chance to download the dataset directly, as it would avoid possible inconsistencies.
Also, there shouldn't be any legal issue given that it is licensed under Creative Commons :-)

**Comment by StephenHausler** [comment]
Hi @gmberton,
We hadn't planned to release it, but it is something we can look into.
It is quite a large dataset, I'll investigate over the next couple weeks and see if it is possible to create an online download source for our copy of the Nordland dataset.

**Comment by gmberton** [comment]
Thanks @StephenHausler !
If the dataset is too heavy to upload somewhere, perhaps you could write a script to download and post-process it? We did something similar [here](https://github.com/gmberton/datasets_vg) with other datasets.
Also, if it's too much work I'd be happy to contribute.

**Comment by MAX-OTW** [comment]
Hello, @StephenHausler @Tobias-Fischer ,I really appreciate for your great work. I agree with @gmberton  that you should give specific information about the datasets used in the paper, such as the range used, the source of the data set, etc.Even better, give the direct download link to the dataset and give the corresponding partition code.
Also, if it's too much work I'd be happy to contribute with @gmberton together!
I hope you will take this proposal into serious consideration and I look forward to receiving your reply~
Best regards.

**Comment by StephenHausler** [comment]
Hi @gmberton and @MAX-OTW, sorry this has taken a while to complete.
We have now created a public copy of the dataset, which is available at:
https://cloudstor.aarnet.edu.au/plus/s/2LtwUtLUFpUiUC8
(this contains all the images, its about 45GB of data)

Please try this link and let me know if you can access it ok. This is an early-access for those on this issue, please let me know if you have any feedback! Please note I'm still working on updating the notebook in the folder with updated functions, that will be completed soon.

**Comment by MAX-OTW** [comment]
Hi, @StephenHausler ,thanks for your reply and work!I tried the link above, so far the link is feasible, looking forward to your subsequent work!

**Comment by gmberton** [comment]
Thanks @StephenHausler the link works fine :+1:

**Comment by StephenHausler** [comment]
FYI, since cloudstor has been decommissioned the Nordland dataset can now be downloaded from: https://huggingface.co/datasets/Somayeh-h/Nordland
