### ISSUE TITLE
The training process

### ISSUE THREAD

**Issue by Orbis36** [QVPR/Patch-NetVLAD#58]
Hi, 

Thanks for your excellent work.
Since you haven't provided any multi-card training codes,
I want to know how long time do I need if I want to train the Patch-NetVLAD from scratch? with a 3090.
It seems for the 30 epochs(Default Settings) it will need more than 2 weeks, is that correct?

Thanks for any help

**Comment by Tobias-Fischer** [comment]
Yes, as far as I remember, this is correct.

Please feel free to add a PR to add multi-card training, it should not be too hard to add.


Best, Tobi
/cc @StephenHausler
