### ISSUE TITLE
dataset download URLs

### ISSUE THREAD

**Issue by GeTRight911** [QVPR/Patch-NetVLAD#6]
Where can I download the Pittsburgh dataset，can you give me the url, thank you!

**Comment by Tobias-Fischer** [comment]
Hi @GeTRight911,
You may request the dataset here: https://www.di.ens.fr/willow/research/netvlad/ (this contains information for the Tokyo24/7 dataset as well).
For completeness, the Mapillary dataset can be downloaded from https://github.com/mapillary/mapillary_sls
And the Nordland dataset from https://nrkbeta.no/2013/01/15/nordlandsbanen-minute-by-minute-season-by-season/
