### ISSUE TITLE
download datasets

### ISSUE THREAD

**Issue by libenchong** [QVPR/Patch-NetVLAD#61]
Hello, I really appreciate for the work you've done.I have meet some trouble with these datasets(pitts30-k,tokyo247,norland datasets) not found.Can you provide these datasets? I did not find the download links for these datasets from the Internet or some of the links are inaccessible.

**Comment by Tobias-Fischer** [comment]
For Tokyo and Pitts please contact the authors of the respective papers. For Nordland see https://github.com/QVPR/Patch-NetVLAD/issues/57
