### ISSUE TITLE
cannot find the datasets...

### ISSUE THREAD

**Issue by Raywoo1** [QVPR/Patch-NetVLAD#69]
Sir, I haven't found these data sets for a long time... Can you provide the data set used in the article? Thank you very much.

**Comment by Tobias-Fischer** [comment]
Which one?

**Comment by Raywoo1** [comment]
The first one is pitts 30k. ps: I have found the Pittsburgh 250k.
The second one is Mapillary street Level Sequences. I mean, i havē found this dataset, but there are so many files, I don't know which one is used in this paper.
![image](https://user-images.githubusercontent.com/28223203/223661288-d9d034d1-62e3-4e6d-9877-baebd03cae87.png)
Just like Mapillary street Level Sequences, the extended CMU Seasons has a lot of files too, should i download everyone?
![image](https://user-images.githubusercontent.com/28223203/223661932-1c1c9220-1133-483f-9e2c-900dae83c76e.png)

So, the basic question is, I don't know whether that file all need to be downloaded.
Thank you so so much! AND, THOSE FILES ARE SO BIG!

**Comment by Tobias-Fischer** [comment]
Please see https://github.com/QVPR/Patch-NetVLAD/issues/61 - for Pitts you'll need to contact the authors of the paper, we don't have the rights to distribute those datasets. There is some version [here](https://surfdrive.surf.nl/files/index.php/s/sbZRXzYe3l0v67W) but I never tried it.

For MSLS, you seem to have found it - yes, those files are big.
