### ISSUE TITLE
About score of the similarity

### ISSUE THREAD

**Issue by noah003** [QVPR/Patch-NetVLAD#7]
hi, 
It looks like the score is not normalized, how to distinguish between larger and lower scores

**Comment by StephenHausler** [comment]
Hi noah003,

The similarity score is normalized, please see L167 of patchnetvlad/models/local_matcher.py.
The normalization function ensures that all patch sizes are weighted according to the patch weights configuration and not biased in any other way.

Please let me know if this answers your query.
