### ISSUE TITLE
How to arrange the mapillary dataset when training the code

### ISSUE THREAD

**Issue by bestwo01** [QVPR/Patch-NetVLAD#70]
Hi, Professor. 
I am very interested in patch-netvlad code that you posted on github. I want to train the code by myself, but there are some problems that I hope you can help me. So, when I use the command as follows, there is an error: unrecognized arguments: dataset_root(the root directory name of mapillary dataset).
`python train.py \
--config_path patchnetvlad/configs/train.ini \
--cache_path=/path/to/your/desired/cache/folder \
--save_path=/path/to/your/desired/checkpoint/save/folder \
--dataset_root_dir=/path/to/your/mapillary/dataset`

The mapillary dataset contains those files, and I just downloaded the msls_images_vol_6 which contains, test and train_val, two folders. I arranged it as follows. Should I put all the pictures under the dataset_root directory or just arrange as follows:
![image](https://user-images.githubusercontent.com/114481346/224546815-34718ff5-9427-4ad7-abf7-63084cbfa7bb.png)

![arrange dataset](https://user-images.githubusercontent.com/114481346/224546759-b37807c4-c883-44f4-be02-95d3ee7c921f.png)

**Comment by Tobias-Fischer** [comment]
Hi,

Re folder structure: it should be a flat structure, i.e. `$dataset_root_dir/test` etc.

Re the error `unrecognized arguments: dataset_root`: The correct argument is called `dataset_root_dir`.

Feel free to reopen if you have any more questions :).


Best, Tobi

**Comment by bestwo01** [comment]
Hi, Professor. Thanks for your replying. I arrange the dataset as follows:
![0a693dc23426871431d1f1b6eee0c43](https://user-images.githubusercontent.com/114481346/224606280-6ec0e14a-2dc7-48b4-b606-32f5a41bd932.png)
I run the code using a command like this, but it still shows unrecognized argument: dataset_root_dir
![fbe6f458472d674f26b11b499a20f7c](https://user-images.githubusercontent.com/114481346/224606496-95537b97-00d3-487e-9d1d-ef60fd455afb.png)

**Comment by Tobias-Fischer** [comment]
Can you copy+paste the exact command that you use, please?

**Comment by bestwo01** [comment]
I used this command:
python train.py --config_path patchnetvlad/configs/train.ini --cache_path cache --save_path checkpoint --dataset_root_dir dataset_root_dir

cache and checkpoint are folders that I created

**Comment by bestwo01** [comment]
I used this command:
python train.py --config_path patchnetvlad/configs/train.ini --cache_path cache --save_path checkpoint --dataset_root_dir dataset_root_dir

cache and checkpoint are folders that I created

**Comment by Tobias-Fischer** [comment]
Apologies but I cannot replicate your issue. In the screenshot above, you may have forgotten the `--` ahead of `dataset_root_dir`, and a space between `checkpoint` and `--` causing the problem. If I run 
`python train.py --config_path patchnetvlad/configs/train.ini --cache_path cache --save_path checkpoint --dataset_root_dir dataset_root_dir` everything works as intended.

**Comment by bestwo01** [comment]
Thank you very much, there is a space causing the problem.
