### ISSUE TITLE
How to get the value of Extended CMU Seasons?

### ISSUE THREAD

**Issue by MAX-OTW** [QVPR/Patch-NetVLAD#71]
Hello @Tobias-Fischer @StephenHausler ,I really appreciate for your work.
I have a question, the Supplementary Table 2 shows that the result of Extended CMU Seasons of Patch-NetVLAD:
Urban:19.2 / 48.0 / 97.2; 
Suburban:8.2 / 28.8 / 97.0; 
Park:9.5 / 34.9 / 94.3

But in the Table 1,the result is :
11.8/36.2/96.2

Is it weighted in some way? How is it converted?
I am always looking forward to your kind response.
Best regards.

**Comment by Tobias-Fischer** [comment]
Hi @MAX-OTW - as far as I can remember, the main paper contains the weighted average (by number of images) of what is shown in Supp. Table 2 (where the dataset is split by condition). I hope this helps :)

**Comment by Tobias-Fischer** [comment]
Do you have the datasets at hand? It should be easy to calculate the weighted mean given the number of images per condition. Please see https://github.com/QVPR/Patch-NetVLAD/issues/45 re RobotCar v2 - @StephenHausler is still looking into this (he has moved to a new position, so unfortunately only has limited time to look into this).

**Comment by Tobias-Fischer** [comment]
Hi,
Park: 32322
Suburban: 43224
Urban: 31200
Please check out the Extended CMU readme to figure out the file paths based on the slices.

With these numbers, the weighted average is exactly as written in the paper, e.g. (32322*9.5+43224*8.2+31000*19.2)/(32322+43224+31000)=11.8

The results were obtained on the benchmark, but we did not make the results public.
