### ISSUE TITLE
Small issue on feature_match

### ISSUE THREAD

**Issue by doraemon96** [QVPR/Patch-NetVLAD#72]
On the `feature_match.py` file there's a small bug in:
https://github.com/QVPR/Patch-NetVLAD/blob/main/feature_match.py#L141
where you do:
```
faiss_index.search(qFeat, min(len(qFeat), max(n_values)))
```
I believe your intention was to restrict the search to return at most `len(dbFeat)` elements, which is the size of the faiss index.
```
faiss_index.search(qFeat, min(len(dbFeat), max(n_values)))
```

Very interesting paper and implementation, kudos!

**Comment by Tobias-Fischer** [comment]
Good catch. Could you please open a pull request so the change is properly attributed to you?
