### ISSUE TITLE
problem on training

### ISSUE THREAD

**Issue by bestwo01** [QVPR/Patch-NetVLAD#75]
Hello, professors. When I tried to train the MSLS dataset, there is an error, do you have any suggestions on this error?
command: 
`python train.py --config_path patchnetvlad/configs/train.ini --cache_path cache --save_path checkpoint --dataset_root_dir Dataset --nocuda`
error:
`ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (441280,) + inhomogeneous part.`
![image](https://user-images.githubusercontent.com/114481346/233389940-29922f7e-1e81-4703-882c-005bbc42e130.png)
![image](https://user-images.githubusercontent.com/114481346/233390032-1e3520ad-52ca-4f06-a0e6-f81c05b85c69.png)

**Comment by bestwo01** [comment]
It seems the training array has wrong dimensions and may be a numpy problem. Could you please tell me which numpy version did you use?

**Comment by Tobias-Fischer** [comment]
1.21 should work

**Comment by bestwo01** [comment]
Thanks for your reply. Which python version did you use?

**Comment by Tobias-Fischer** [comment]
3.9

**Comment by Tian0906** [comment]
Hi, I'm experiencing the same problem, have you solved it yet?

**Comment by Tian0906** [comment]
> Hi, I'm experiencing the same problem, have you solved it yet?

**Comment by vampire1204** [comment]
> Thanks for your reply. Which python version did you use?

I find the same problem, and then change the version of numpy to 1.21.0, it's ok
