### ISSUE TITLE
Remove the WPCA layer before train

### ISSUE THREAD

**Issue by longxiangjingyun** [QVPR/Patch-NetVLAD#76]
Hello, professors! Could you explain in detail how  to remove the WPCA layer before training?
（In the readme.md-->Quick start-->training）
![issue](https://user-images.githubusercontent.com/131769148/234261967-b4f57569-daf5-4ee3-b913-792bbdfd4349.JPG)

**Comment by Tobias-Fischer** [comment]
Can you try:

```
if 'WPCA' in model._modules:
    del model._modules['WPCA']
```

**Comment by Tobias-Fischer** [comment]
Closing for now - feel free to reopen if above doesn’t work.

**Comment by longxiangjingyun** [comment]
First, I'm glad to get your answer. I already solve the problems. But I get a new prblem and I will discribe it.
In train.py, some keys(line130--epoch, line197--optimizer, line223,224--not_improved,best_score) are not defined in the mapillary_WPCA128.pth pre-model. these pre-models just include 'num_pcs', 'state_dict'. So I can't use pre-models of download files. If conditions permit, can you share the pre-models for adapting the trian.py. I would like to express my sincere gratitude here.

**Comment by Tobias-Fischer** [comment]
Simply comment out these lines.
