### ISSUE TITLE
questions about grouth.npz

### ISSUE THREAD

**Issue by WentangChen** [QVPR/Patch-NetVLAD#83]
hi
thank you for sharing your excellent work!
I am trying to make my ground_truth.npz for my own dataset. but I have some questions:
1. does 'utmQ' and 'utmQ' contains the utm coordinates of **all** pictures in query and database dataset?
2. I have create my datasets with 7 places. Each place have 400 pictures for database and 80 pictures for query. is the number of pictures enough for training (simply using the traning code provided for maliipary dataset)?
3. I have try training on my own dataset (descirbed in question 2.). And I got the following result:

====> Calculating recall @ N                                                    
====> Recall@1: 0.0600                                                          
====> Recall@5: 0.1200                                                          
====> Recall@10: 0.1800                                                         
====> Recall@20: 0.3000                                                         
====> Recall@50: 0.6000                                                         
====> Recall@100: 0.8200 

I wonder the result is good or not?

I am looking forward to your reply , thank you!

**Comment by Tobias-Fischer** [comment]
Hi,
1. Yes
2. No, this is most likely not sufficient. But why not use a pre trained model and use that to extract features on your dataset?
3. The results look poor considering there are only 7 places.

You might want to read our recent “Visual Place Recognition: A Tutorial” paper for some more intuitions.
