### ISSUE TITLE
Unable to download pretrained models

### ISSUE THREAD

**Issue by lijincheng2020** [QVPR/Patch-NetVLAD#90]
Hello,

Thanks for your work!

I followed readme and tried to download those pretrained models on the websites that you have provided, only to find "**CloudStor has been decommissioned. As of 12pm AEDT on 15 December 2023 you can no longer access CloudStor.**".

Could you please give me some alternatives so that i could get access to download those pretrained models?

Thanks again!

**Comment by Tobias-Fischer** [comment]
I fixed the links in the README and download_models.py :)
